export const VehClass = {
  Compact: 0,
  Sedan: 1,
  SUV: 2,
  Coupe: 3,
  Muscle: 4,
  SportsClassic: 5,
  Sport: 6,
  Super: 7,
  Motorcyle: 8,
  Offroad: 9,
  Industrial: 10,
  Utility: 11,
  Vans: 12,
  Cycle: 13,
  Boat: 14,
  Helicopter: 15,
  Plane: 16,
  Service: 17,
  Emergency: 18,
  Military: 19,
  Commercial: 20,
  Train: 21,
  OpenWheel: 22,
}

export const damageMultiplyer = {
  [VehClass.Motorcyle]: 0.8,
  [VehClass.Offroad]: 0.4,
  [VehClass.Super]: 1.5,
  [VehClass.Sport]: 1.2,
  [VehClass.Military]: 0.2,
}
